### ISSUE TITLE
What is the license for this repository?

### ISSUE THREAD

**Issue by ahmaxed** [Joon174/Square_Hacks#9]
Thank you for this solution.

It definitely saved me a lot of time.
I was wondering what is the license for this repo so I could use it accordingly.

Thank you

**Comment by ahmaxed** [comment]
@ZweatMonash :)

**Comment by ZweatMonash** [comment]
@ahmadabdolsaheb MIT License. Happy that you found it useful. If you don't mind sharing, what are you working on?

**Comment by ahmaxed** [comment]
Great,  just made a pr to include that (#10 )
We are planning to use your card from collect donations at freeCodeCamp :)
